version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
    interval: "weekly"
    day: "monday"
    time: "08:00"
    groups:
      straightforward-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
